environments:
  prod:
    test:
      environment_variable: OSTYPE=linux-gnu
    port: 80
  local:
    test:
      environment_variable: "HOMEDRIVE=C:"
    port: 5000




all:
  coinbase:
    api_key: "FROM CREDENTIALS FILE"
    api_secret: "FROM CREDENTIALS FILE"

  google:
    gdrive:




prod:




local:
